package com.fqueue.dto;
// Generated Dec 26, 2008 4:49:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Branchservicedetail generated by hbm2java
 */

public class Branchservicedetail  implements java.io.Serializable {


    // Fields    

     private BranchservicedetailId id;
     private String ipAddress;


    // Constructors

    /** default constructor */
    public Branchservicedetail() {
    }

	/** minimal constructor */
    public Branchservicedetail(BranchservicedetailId id) {
        this.id = id;
    }
    
    /** full constructor */
    public Branchservicedetail(BranchservicedetailId id, String ipAddress) {
        this.id = id;
        this.ipAddress = ipAddress;
    }
    

   
    // Property accessors

    public BranchservicedetailId getId() {
        return this.id;
    }
    
    public void setId(BranchservicedetailId id) {
        this.id = id;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
   








}
