package com.fqueue.dto;
// Generated Dec 26, 2008 4:49:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Parameter generated by hbm2java
 */

public class Parameter  implements java.io.Serializable {


    // Fields    

     private String code;
     private String value;
     private String description;


    // Constructors

    /** default constructor */
    public Parameter() {
    }

	/** minimal constructor */
    public Parameter(String code) {
        this.code = code;
    }
    
    /** full constructor */
    public Parameter(String code, String value, String description) {
        this.code = code;
        this.value = value;
        this.description = description;
    }
    

   
    // Property accessors

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}
