package com.fqueue.dto;
// Generated Dec 26, 2008 4:49:23 PM by Hibernate Tools 3.1.0.beta4



/**
 * Servicerole generated by hbm2java
 */

public class Servicerole  implements java.io.Serializable {


    // Fields    

     private String serviceId;
     private String role;
     private String description;


    // Constructors

    /** default constructor */
    public Servicerole() {
    }

	/** minimal constructor */
    public Servicerole(String serviceId, String role) {
        this.serviceId = serviceId;
        this.role = role;
    }
    
    /** full constructor */
    public Servicerole(String serviceId, String role, String description) {
        this.serviceId = serviceId;
        this.role = role;
        this.description = description;
    }
    

   
    // Property accessors

    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   








}
